if(typeof(ContactSync2)=== "undefined"){ ContactSync2 = {}; }

//API call will trigger ContactSync2 reset
ContactSync2.reset = function(successcallback,errorcallback){
	if(!kony.sync.isSyncInitialized(errorcallback)){
		return;
	}
	kony.sync.scopeReset("ContactSync2",successcallback,errorcallback);
}



if(typeof(AccountSync)=== "undefined"){ AccountSync = {}; }

//API call will trigger AccountSync reset
AccountSync.reset = function(successcallback,errorcallback){
	if(!kony.sync.isSyncInitialized(errorcallback)){
		return;
	}
	kony.sync.scopeReset("AccountSync",successcallback,errorcallback);
}



if(typeof(LeadSync)=== "undefined"){ LeadSync = {}; }

//API call will trigger LeadSync reset
LeadSync.reset = function(successcallback,errorcallback){
	if(!kony.sync.isSyncInitialized(errorcallback)){
		return;
	}
	kony.sync.scopeReset("LeadSync",successcallback,errorcallback);
}



if(typeof(OpportunitySync)=== "undefined"){ OpportunitySync = {}; }

//API call will trigger OpportunitySync reset
OpportunitySync.reset = function(successcallback,errorcallback){
	if(!kony.sync.isSyncInitialized(errorcallback)){
		return;
	}
	kony.sync.scopeReset("OpportunitySync",successcallback,errorcallback);
}




// **********************************Start Scope definition************************
konysyncClientSyncConfig ={
     "ArrayOfSyncScope": [
          {
               "DataSource": "41f6a29c-3184-4098-ae8e-cb3746949c4b",
               "ScopeName": "ContactSync2",
               "ScopeDatabaseName": "b972d075-dd15-4910-ac1c-9edda03ea089",
               "Strategy": "OTA_SYNC",
               "ScopeTables": [{
                    "Name": "Contact",
                    "Columns": [
                         {
                              "Name": "AccountId",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "AssistantName",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "AssistantPhone",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Birthdate",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "CleanStatus",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "CreatedById",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "CreatedDate",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Department",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Description",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Email",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "EmailBouncedDate",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "EmailBouncedReason",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Fax",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "FirstName",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "HomePhone",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Id",
                              "Autogenerated": "true",
                              "IsPrimaryKey": true,
                              "IsNullable": false,
                              "type": "string"
                         },
                         {
                              "Name": "IsEmailBounced",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "boolean"
                         },
                         {
                              "Name": "Jigsaw",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "JigsawContactId",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Languages__c",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "LastActivityDate",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "LastCURequestDate",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "LastCUUpdateDate",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "LastModifiedById",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "LastName",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "LastReferencedDate",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "LastViewedDate",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "LeadSource",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Level__c",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "MailingAddress",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "MailingCity",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "MailingCountry",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "MailingLatitude",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "MailingLongitude",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "MailingPostalCode",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "MailingState",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "MailingStreet",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "MasterRecordId",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "MobilePhone",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Name",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "OtherAddress",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "OtherCity",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "OtherCountry",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "OtherLatitude",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "OtherLongitude",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "OtherPhone",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "OtherPostalCode",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "OtherState",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "OtherStreet",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "OwnerId",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Phone",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "PhotoUrl",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "ReportsToId",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Salutation",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "SystemModstamp",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Title",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "errorCode",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "message",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "moreRecordsAvailable",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "queryIdentifier",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "queryString",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         }
                    ],
                    "Pk_Columns": ["Id"],
                    "Relationships": {}
               }]
          },
          {
               "DataSource": "8fd334ca-8e65-439f-8dae-6b67c5a195a7",
               "ScopeName": "AccountSync",
               "ScopeDatabaseName": "b972d075-dd15-4910-ac1c-9edda03ea089",
               "Strategy": "OTA_SYNC",
               "ScopeTables": [{
                    "Name": "Account",
                    "Columns": [
                         {
                              "Name": "AccountNumber",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "AccountSource",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Active__c",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "AnnualRevenue",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "BATCH_SIZE",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "BillingAddress",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "BillingCity",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "BillingCountry",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "BillingLatitude",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "BillingLongitude",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "BillingPostalCode",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "BillingState",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "BillingStreet",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "CleanStatus",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "CreatedById",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "CreatedDate",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "CustomerPriority__c",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "DandbCompanyId",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Description",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "DunsNumber",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Fax",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Id",
                              "Autogenerated": "true",
                              "IsPrimaryKey": true,
                              "IsNullable": false,
                              "type": "string"
                         },
                         {
                              "Name": "Industry",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Jigsaw",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "JigsawCompanyId",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "LastActivityDate",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "LastModifiedById",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "LastReferencedDate",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "LastViewedDate",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "MasterRecordId",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "NaicsCode",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "NaicsDesc",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Name",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "NumberOfEmployees",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "NumberofLocations__c",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "OwnerId",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Ownership",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "ParentId",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Phone",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "PhotoUrl",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Rating",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "SLAExpirationDate__c",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "SLASerialNumber__c",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "SLA__c",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "START_TIME",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "ShippingAddress",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "ShippingCity",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "ShippingCountry",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "ShippingLatitude",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "ShippingLongitude",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "ShippingPostalCode",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "ShippingState",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "ShippingStreet",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Sic",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "SicDesc",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Site",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "SystemModstamp",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "TickerSymbol",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Tradestyle",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Type",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "UpsellOpportunity__c",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Website",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "YearStarted",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "errorCode",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "message",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "moreRecordsAvailable",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "queryIdentifier",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "queryString",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         }
                    ],
                    "Pk_Columns": ["Id"],
                    "Relationships": {}
               }]
          },
          {
               "DataSource": "3bc7607f-3ab3-49fa-b6ee-0dbf1f3a9170",
               "ScopeName": "LeadSync",
               "ScopeDatabaseName": "b972d075-dd15-4910-ac1c-9edda03ea089",
               "Strategy": "OTA_SYNC",
               "ScopeTables": [{
                    "Name": "Lead",
                    "Columns": [
                         {
                              "Name": "Address",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "AnnualRevenue",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "BATCH_SIZE",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "City",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "CleanStatus",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Company",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "CompanyDunsNumber",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "ConvertedAccountId",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "ConvertedContactId",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "ConvertedDate",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "ConvertedOpportunityId",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Country",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "CreatedById",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "CreatedDate",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "CurrentGenerators__c",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "DandbCompanyId",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Description",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Email",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "EmailBouncedDate",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "EmailBouncedReason",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Fax",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "FirstName",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Id",
                              "Autogenerated": "true",
                              "IsPrimaryKey": true,
                              "IsNullable": false,
                              "type": "string"
                         },
                         {
                              "Name": "Industry",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "IsConverted",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "boolean"
                         },
                         {
                              "Name": "IsUnreadByOwner",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "boolean"
                         },
                         {
                              "Name": "Jigsaw",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "JigsawContactId",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "LastActivityDate",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "LastModifiedById",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "LastName",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "LastReferencedDate",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "LastViewedDate",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Latitude",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "LeadSource",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Longitude",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "MasterRecordId",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "MobilePhone",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Name",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "NumberOfEmployees",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "NumberofLocations__c",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "OwnerId",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Phone",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "PhotoUrl",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "PostalCode",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Primary__c",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "ProductInterest__c",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Rating",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "SICCode__c",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "START_TIME",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Salutation",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "State",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Status",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Street",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "SystemModstamp",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Title",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Website",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "errorCode",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "message",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "moreRecordsAvailable",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "queryIdentifier",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "queryString",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         }
                    ],
                    "Pk_Columns": ["Id"],
                    "Relationships": {}
               }]
          },
          {
               "DataSource": "65fdac09-5fae-4785-88ca-f04a8ad16fc9",
               "ScopeName": "OpportunitySync",
               "ScopeDatabaseName": "b972d075-dd15-4910-ac1c-9edda03ea089",
               "Strategy": "OTA_SYNC",
               "ScopeTables": [{
                    "Name": "Opportunity",
                    "Columns": [
                         {
                              "Name": "AccountId",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Amount",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "BATCH_SIZE",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "CampaignId",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "CloseDate",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "CreatedById",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "CreatedDate",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "CurrentGenerators__c",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "DeliveryInstallationStatus__c",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Description",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "ExpectedRevenue",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Fiscal",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "FiscalQuarter",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "FiscalYear",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "ForecastCategory",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "ForecastCategoryName",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "HasOpportunityLineItem",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "boolean"
                         },
                         {
                              "Name": "Id",
                              "Autogenerated": "true",
                              "IsPrimaryKey": true,
                              "IsNullable": false,
                              "type": "string"
                         },
                         {
                              "Name": "IsClosed",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "boolean"
                         },
                         {
                              "Name": "IsPrivate",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "boolean"
                         },
                         {
                              "Name": "IsWon",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "boolean"
                         },
                         {
                              "Name": "LastActivityDate",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "LastModifiedById",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "LastReferencedDate",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "LastViewedDate",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "LeadSource",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "MainCompetitors__c",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Name",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "NextStep",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "OrderNumber__c",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "OwnerId",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Pricebook2Id",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Probability",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "START_TIME",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "StageName",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "SystemModstamp",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "TotalOpportunityQuantity",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "TrackingNumber__c",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "Type",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "errorCode",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "message",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "moreRecordsAvailable",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "queryIdentifier",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         },
                         {
                              "Name": "queryString",
                              "Autogenerated": "false",
                              "IsNullable": true,
                              "type": "string"
                         }
                    ],
                    "Pk_Columns": ["Id"],
                    "Relationships": {}
               }]
          }
     ],
     "ArrayOfDataSource": [
          {
               "ID": "41f6a29c-3184-4098-ae8e-cb3746949c4b",
               "type": "RESTFUL"
          },
          {
               "ID": "8fd334ca-8e65-439f-8dae-6b67c5a195a7",
               "type": "RESTFUL"
          },
          {
               "ID": "3bc7607f-3ab3-49fa-b6ee-0dbf1f3a9170",
               "type": "RESTFUL"
          },
          {
               "ID": "65fdac09-5fae-4785-88ca-f04a8ad16fc9",
               "type": "RESTFUL"
          }
     ],
     "AppID": "b972d075-dd15-4910-ac1c-9edda03ea089",
     "Version": "d93c8e6f7a222e1605b2c0552ffcccdc13552bbad878717294b625d9aa4ab222"
}
//**********************************End Scope definition************************
